#pragma once
#define DROP
#include "std_include.cpp"
//#include "compiler_hint.cpp"
#include "multi_dimensional_vector.cpp"
#include "constant.cpp"
#include "debug.cpp"
#include "macros.cpp"
#include "random.cpp"
#include "timer.cpp"
#include "alias.cpp"
//#include "array_adder.cpp"
